pipelines:
  default:
    - step:
        name: Mirror to GitHub
        image: atlassian/default-image:3
        script:
          - apt-get update && apt-get install -y git
          - git config --global user.name "$GITHUB_USERNAME"
          - git config --global user.email "$GITHUB_USERNAME@users.noreply.github.com"
          # Add GitHub remote using token for authentication
          - git remote add mirror https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/StockPort.git
          # Push all branches and tags to GitHub
          - git push mirror --all --force
          - git push mirror --tags --force
