pipelines:
  branches:
    develop:
      - step:
          name: Mirror develop branch to GitHub
          image: atlassian/default-image:3
          script:
            - apt-get update && apt-get install -y git
            - git config --global user.name "$GITHUB_USERNAME"
            - git config --global user.email "$GITHUB_USERNAME@users.noreply.github.com"
            - git remote add mirror https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/StockPort.git
            - git push mirror develop --force
            - git push mirror --tags --force
