"""
AuthX Storage Interface

Defines the abstract storage interface for authentication and licensing.
Implementations can use SQLite, Postgres, or any other backend.
"""

from __future__ import annotations
from typing import Protocol, Optional, Dict, Any, List
from datetime import datetime

class AuthStorage(Protocol):
    # User management
    def create_user(self, username: str, email: str, password: str, is_admin: bool = False) -> int: ...
    def update_password(self, user_id: int, new_password: str) -> None: ...
    def get_user_by_id(self, user_id: int) -> Optional[Dict[str, Any]]: ...
    def get_user_by_email(self, email: str) -> Optional[Dict[str, Any]]: ...
    def get_user_by_username(self, username: str) -> Optional[Dict[str, Any]]: ...
    def verify_password(self, user_id: int, password: str) -> bool: ...

    # Sessions
    def create_session(self, user_id: int, expires_hours: int = 24) -> str: ...
    def get_session(self, session_token: str) -> Optional[Dict[str, Any]]: ...
    def delete_session(self, session_token: str) -> None: ...
    def cleanup_expired_sessions(self) -> None: ...

    # Licensing
    def create_license(self, user_id: int, plan_type: str, expires_days: int = 365,
                       stripe_subscription_id: Optional[str] = None,
                       stripe_customer_id: Optional[str] = None) -> str: ...
    def get_active_license(self, user_id: int) -> Optional[Dict[str, Any]]: ...
    def get_license_by_key(self, license_key: str) -> Optional[Dict[str, Any]]: ...
    def update_license_expiry(self, license_id: int, expires_days: int) -> None: ...
    def deactivate_license(self, license_id: int) -> None: ...
    def get_user_licenses(self, user_id: int) -> List[Dict[str, Any]]: ...

    # Admin
    def get_all_users(self) -> List[Dict[str, Any]]: ...

    # Social logins
    def add_social_login(self, user_id: int, provider: str, provider_user_id: str,
                         access_token: Optional[str] = None, refresh_token: Optional[str] = None,
                         expires_at: Optional[datetime] = None) -> None: ...
    def get_social_login(self, provider: str, provider_user_id: str) -> Optional[Dict[str, Any]]: ...
