"""
Strategy Signal Model

Represents a signal generated by a strategy evaluation.
"""

from dataclasses import dataclass
from typing import Dict, Any, Optional, List
from datetime import datetime


@dataclass
class StrategyCondition:
    """Represents a condition in a strategy."""
    type: str  # "indicator", "pattern", etc.
    name: str
    operator: str
    value: Any
    weight: float
    met: bool
    score: float


@dataclass
class StrategySignal:
    """
    Represents a trading signal from a strategy.
    
    Attributes:
        signal_id: Unique signal identifier
        strategy_id: Strategy that generated this signal
        opportunity: The opportunity this signal is for
        score: Signal score (0-100)
        confidence: Confidence level (0-1)
        conditions: List of conditions that were evaluated
        entry_price: Recommended entry price
        stop_loss: Stop loss price
        take_profit: Take profit price
        timestamp: When signal was generated
    """
    signal_id: str
    strategy_id: str
    opportunity: 'Opportunity'  # Forward reference
    score: float
    confidence: float
    conditions: List[StrategyCondition]
    entry_price: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    timestamp: Optional[datetime] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'signal_id': self.signal_id,
            'strategy_id': self.strategy_id,
            'opportunity': self.opportunity.to_dict(),
            'score': self.score,
            'confidence': self.confidence,
            'conditions': [
                {
                    'type': c.type,
                    'name': c.name,
                    'operator': c.operator,
                    'value': c.value,
                    'weight': c.weight,
                    'met': c.met,
                    'score': c.score
                }
                for c in self.conditions
            ],
            'entry_price': self.entry_price,
            'stop_loss': self.stop_loss,
            'take_profit': self.take_profit,
            'timestamp': self.timestamp.isoformat() if self.timestamp else None
        }

